### ISSUE TITLE
Install python SDK of selenium

### ISSUE THREAD

**Issue by DennyZhang** [dhoer/chef-selenium2#1]
Looks like current cookbook only enable java selenium SDK.

It would be nice, if it also enable python SDK as well.

=====================
Some more suggestions:
1. enable firefox plugin
2. enable users to auto start selenium server as remote driver
3. wrap up some basic selenium test code or sample guide.

I'd like to contribute with pull request, if we all agree to do that.
Otherwise I'll have to create a new cookbook to chef supermarket then.

**Comment by dhoer** [comment]
A pull request would be great! Can you include chefspec and test-kitchen tests as well?

**Comment by DennyZhang** [comment]
Should be able to send out pull request by this weekend.

**Comment by dhoer** [comment]
I took ownership of selenium this week and pushed the next generation
selenium cookbook to it. Still plan to push you pull request to here and if
I approve it, I will migrate to the code to the new cookbook.

**Comment by DennyZhang** [comment]
Thanks, Dennis.

Just too busy these days

On Sat, Jan 31, 2015 at 11:03 PM, Dennis Hoer <notifications@github.com>
wrote:

> I took ownership of selenium this week and pushed the next generation
> selenium cookbook to it. Still plan to push you pull request to here and
> if
> I approve it, I will migrate to the code to the new cookbook.
>
> On Mon, Jan 26, 2015 at 1:23 PM, DennyZhang(张巍) <notifications@github.com>
>
> wrote:
>
> > Should be able to send out pull request by this weekend.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dhoer/chef-selenium2/issues/1#issuecomment-71531060>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhoer/chef-selenium2/issues/1#issuecomment-72351846>.
>



-- 
Thanks,
Denny
