### ISSUE TITLE
selenium standalone server: start one hub and multiple nodes

### ISSUE THREAD

**Issue by DennyZhang** [dhoer/chef-selenium2#2]
Enable customers to automatically start one hub role and multiple node roles.
https://code.google.com/p/selenium/wiki/Grid2

Thus as end users, we can easily run multiple parallel selenium tests in one machine.

The behavior could be optional, which is specified by chef attributes.

**Comment by dhoer** [comment]
I'm not sure I understand what you are asking. Although not tested; you should be able to configure many hubs and nodes on a single machine. Use resource attributes (e.g., port, hub_port) configure the json config: https://code.google.com/p/selenium/wiki/Grid2#Configuring_the_nodes_by_JSON

**Comment by DennyZhang** [comment]
@dhoer 
My basic motivation is:
- The ability to auto start them
- headless test without x-windows

**Comment by dhoer** [comment]
Have you run the test kitchen tests?  The hub and nodes start
automatically.  I guess a start and stop can be added, but I usually throw
the servers away when I'm done testing or I let users manage nodes via aws
auto-scaling group.

I'm not sure what you mean by headless without x-windows.  I only know of
xvfb or x11vnc. What are other alternatives?

**Comment by DennyZhang** [comment]
Let me try kitchen tests first, then get back for this.

When I say headless of selenium, I mean xvfb.

On Mon, Jan 26, 2015 at 4:37 PM, Dennis Hoer <notifications@github.com>
wrote:

> Have you run the test kitchen tests? The hub and nodes start
> automatically. I guess a start and stop can be added, but I usually throw
> the servers away when I'm done testing or I let users manage nodes via aws
> auto-scaling group.
>
> I'm not sure what you mean by headless without x-windows. I only know of
> xvfb or x11vnc. What are other alternatives?
>
>
> On Mon, Jan 26, 2015 at 1:24 PM, DennyZhang(张巍) <notifications@github.com>
>
> wrote:
>
> > @dhoer <https://github.com/dhoer>
> > My basic motivation is:
> >
> > - The ability to auto start them
> > - headless test without x-windows
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dhoer/chef-selenium2/issues/2#issuecomment-71531251>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhoer/chef-selenium2/issues/2#issuecomment-71553523>.
>



-- 
Thanks,
Denny

**Comment by dhoer** [comment]
Note that Java, browsers and display alternatives are not part of this
cookbook.  This separation of concern allows more flexibility in how these
components are installed and configured.

Selenium-grid cookbook just focuses on selenium grid install and
configuration.

A display can be physical or headless.  If headless, you have several
alternatives to choose from that is outside the concern of this cookbook.

**Comment by DennyZhang** [comment]
Dennis, got it. Thanks.

On Mon, Jan 26, 2015 at 5:09 PM, Dennis Hoer <notifications@github.com>
wrote:

> Note that Java, browsers and display alternatives are not part of this
> cookbook. This separation of concern allows more flexibility in how these
> components are installed and configured.
>
> Selenium-grid cookbook just focuses on selenium grid install and
> configuration.
>
> A display can be physical or headless. If headless, you have several
> alternatives to choose from that is outside the concern of this cookbook.
>
> On Mon, Jan 26, 2015 at 3:41 PM, DennyZhang(张巍) <notifications@github.com>
>
> wrote:
>
> > Let me try kitchen tests first, then get back for this.
> >
> > When I say headless of selenium, I mean xvfb.
> >
> > On Mon, Jan 26, 2015 at 4:37 PM, Dennis Hoer <notifications@github.com>
> > wrote:
> >
> > > Have you run the test kitchen tests? The hub and nodes start
> > > automatically. I guess a start and stop can be added, but I usually
> > throw
> > > the servers away when I'm done testing or I let users manage nodes via
> > aws
> > > auto-scaling group.
> > >
> > > I'm not sure what you mean by headless without x-windows. I only know
> of
> > > xvfb or x11vnc. What are other alternatives?
> > >
> > >
> > > On Mon, Jan 26, 2015 at 1:24 PM, DennyZhang(张巍) <
> > notifications@github.com>
> > >
> > > wrote:
> > >
> > > > @dhoer <https://github.com/dhoer>
> > > > My basic motivation is:
> > > >
> > > > - The ability to auto start them
> > > > - headless test without x-windows
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/dhoer/chef-selenium2/issues/2#issuecomment-71531251>.
>
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/dhoer/chef-selenium2/issues/2#issuecomment-71553523>.
> >
> > >
> >
> >
> >
> > --
> > Thanks,
> > Denny
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dhoer/chef-selenium2/issues/2#issuecomment-71554052>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhoer/chef-selenium2/issues/2#issuecomment-71558274>.
>



-- 
Thanks,
Denny
